#services:
#    hwi_oauth.user.provider.entity:
#        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
#    ib_user.oauth_user_provider:
#        class: Acme\DemoBundle\Auth\OAuthProvider
#        arguments: [@session, @doctrine, @service_container]